!! Generated by {{developer}} - {{local_time}}
service password-encryption
no service pad
no ip forward-protocol nd
no ip source-route
ip dhcp bootp ignore
clock timezone CET 1 0
clock summer-time CEST recurring last Sun Mar 2:00 last Sun Oct 3:00
service timestamps log datetime localtime show-timezone
logging buffered 4096
no ip http server
no ip http secure-server
{{config_str}}